### PR TITLE
replace tap with node --test

### PR DESCRIPTION
**Pull request by msimerson**
This PR requires a little more consideration. Factors:

- it gets rid of a dependency
  - that requires semi-frequent updates
  - that adds 5100 lines to package-lock.json
- the test output from `node --test` isn't as good as tap
- node --test does not do automatic coverage testing
  - `npm run cover` will do it (script added)
- coverage testing can also be done with a GitHub Action workflow
  - included in this PR

### CODE REVIEW

**Comment by jackbearheart** [comment]
Could use a rebase now.

**Comment by msimerson** [comment]
done.

**Comment by jackbearheart** [comment]
Thanks. I think it re-deletes tests.xml.

**Comment by msimerson** [comment]
Indeed. Fixed.

**Pull request merged**
