### PR TITLE
Allow comma in display name

### PR DESCRIPTION
**Pull request by osm**

### CODE REVIEW

**Comment by jackbearheart** [comment]
Hey, thanks for the PR.

A goal of this project is to implement email address parsing as per the specs published in RFCs. The comment you edited isn't a line we wrote, but is the original spec from rfc 5322. Unless you know of another document that supersedes this and allows commas, we can't just edit that.

However, I understand that this exception might be useful to people. We could add it to this library if we hide it behind an option flag.

**Comment by osm** [comment]
Thanks for great feedback. I have now published a new commit that adds a new option called `commaInDisplayName`, which works in a similar way as the `atInDisplayName`-option.

**Comment by osm** [comment]
Hi,

Just wanted to ping you @jackbearheart in case you missed the new commits in the PR.

**Comment by jackbearheart** [comment]
@osm Sorry for the delay. Thanks for this PR, it looks good!

**Pull request merged**
